import { createHash } from "node:crypto";
import { mkdir, realpath, writeFile } from "node:fs/promises";
import path from "node:path";
import {
  evaluationBindingDigest,
  loadFrozenEvaluationSuite,
  loadMigrationTargetSuite,
  buildEvaluationPrompt,
  readSanitizedCandidateMaterial,
  readSanitizedBaselineMaterial,
  snapshotCandidate,
  snapshotBaselineForCandidate,
  selectEvaluationCases,
  SELF_IMPROVE_CANONICAL_CORPUS,
  SELF_IMPROVE_MIGRATION_SOURCE_CORPUS,
  ordinaryCorpusForBaseline
} from "./self-improve.mjs";
import { binaryIdentity } from "./providers.mjs";

const HOST_TRUST_TOOL = "/private/var/db/better-workflows/bin/bw-host-trust.mjs";
const HOST_ADMIN_SHELL = [
  "set -eu",
  "runtime=\"$1\"",
  "expected=\"$2\"",
  "manifest=\"$3\"",
  "manifest_digest=\"$4\"",
  "target=\"/private/var/db/better-workflows/bin/bw-host-node.$expected\"",
  "actual=$(/usr/bin/shasum -a 256 \"$runtime\" | /usr/bin/awk '{print $1}')",
  "[ \"$actual\" = \"$expected\" ] || { echo 'runtime digest mismatch before staging' >&2; exit 126; }",
  "if [ -e \"$target\" ]; then [ ! -L \"$target\" ] && [ -f \"$target\" ] && [ \"$(/usr/bin/stat -f %u \"$target\")\" = \"0\" ] && [ \"$(/usr/bin/stat -f %Lp \"$target\")\" = \"755\" ] || { echo 'existing runtime target is not root-owned 0755' >&2; exit 126; }; else /bin/cp \"$runtime\" \"$target\"; /usr/sbin/chown root:wheel \"$target\"; /bin/chmod 755 \"$target\"; fi",
  "actual=$(/usr/bin/shasum -a 256 \"$target\" | /usr/bin/awk '{print $1}')",
  "[ \"$actual\" = \"$expected\" ] || { echo 'root runtime digest mismatch after staging' >&2; exit 126; }",
  "exec /usr/bin/env -i PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin \"$target\" \"${HOST_TRUST_TOOL}\" execute-batch --manifest \"$manifest\" --confirm-digest \"$manifest_digest\""
].join("\n");

export async function generateAttestationRequests({
  repo,
  runId,
  baselineRevision,
  candidateRoot,
  model,
  outputDirectory,
  binaryPath = null,
  casesFile = null,
  purpose = "ordinary",
  nextCasesFile = null
}) {
  const resolvedRepo = await realpath(repo);
  const binary = binaryPath
    ? await binaryIdentity(binaryPath)
    : await binaryIdentity("codex");
  const runtime = await binaryIdentity(process.execPath);
  const resolvedBinary = binary.path;
  if (binaryPath && resolvedBinary !== binaryPath) {
    throw new Error("Codex binary argument must already be canonical");
  }
  const outputDir = path.resolve(outputDirectory);
  if (
    outputDir === resolvedRepo ||
    outputDir.startsWith(`${resolvedRepo}${path.sep}`)
  ) {
    throw new Error("Attestation requests must be written outside the repository");
  }
  const defaultCasesFile = purpose === "evaluator-migration"
    ? SELF_IMPROVE_MIGRATION_SOURCE_CORPUS
    : await ordinaryCorpusForBaseline({ cwd: resolvedRepo, baselineRevision });
  const frozen = await loadFrozenEvaluationSuite({
    cwd: resolvedRepo,
    casesFile: path.resolve(
      resolvedRepo,
      casesFile ?? defaultCasesFile
    ),
    baselineRevision,
    canonical: true,
    purpose
  });
  const target = purpose === "evaluator-migration"
    ? await loadMigrationTargetSuite({
      cwd: resolvedRepo,
      casesFile: path.resolve(resolvedRepo, nextCasesFile ?? SELF_IMPROVE_CANONICAL_CORPUS)
    })
    : null;
  const suiteDigest = evaluationBindingDigest({
    purpose,
    sourceSuiteDigest: frozen.sourceDigest,
    targetSuiteDigest: target?.sourceDigest
  });
  const candidate = await snapshotCandidate({
    cwd: resolvedRepo,
    baselineRevision: frozen.baselineRevision,
    candidateRoot
  });
  const candidateMaterial = await readSanitizedCandidateMaterial({
    cwd: resolvedRepo,
    snapshot: candidate
  });
  const baseline = await snapshotBaselineForCandidate({ cwd: resolvedRepo, snapshot: candidate });
  const baselineMaterial = await readSanitizedBaselineMaterial({ cwd: resolvedRepo, snapshot: baseline });
  const promptByRoleAndSplit = new Map();
  if (typeof process.getuid !== "function" || typeof process.getgid !== "function" || process.getuid() <= 0 || process.getgid() <= 0) {
    throw new Error("Execution requests must be generated by the non-root maintainer user");
  }
  const homePath = await realpath(process.env.HOME ?? "").catch(() => {
    throw new Error("Execution requests require a canonical maintainer HOME");
  });
  let codexHomePath = null;
  const requestedCodexHome = process.env.CODEX_HOME ?? path.join(homePath, ".codex");
  try {
    codexHomePath = await realpath(requestedCodexHome);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  const runAs = {
    uid: process.getuid(),
    gid: process.getgid(),
    homePath,
    codexHomePath
  };
  for (const split of ["train", "holdout"]) {
    const cases = selectEvaluationCases({ suite: frozen.suite, snapshot: candidate, split });
    promptByRoleAndSplit.set(`candidate:${split}`, buildEvaluationPrompt({
      suite: { ...frozen.suite, cases },
      candidate,
      materials: candidateMaterial
    }));
    promptByRoleAndSplit.set(`baseline:${split}`, buildEvaluationPrompt({
      suite: { ...frozen.suite, cases },
      candidate: baseline,
      materials: baselineMaterial
    }));
  }
  const executions = [
    { split: "train", role: "train-candidate", attempt: 1 },
    { split: "holdout", role: "candidate", attempt: 1 },
    { split: "holdout", role: "candidate", attempt: 2 },
    { split: "holdout", role: "candidate", attempt: 3 },
    { split: "holdout", role: "baseline", attempt: 1 },
    { split: "holdout", role: "baseline", attempt: 2 },
    { split: "holdout", role: "baseline", attempt: 3 }
  ];
  await mkdir(outputDir, { recursive: false, mode: 0o700 });
  const records = [];
  for (const item of executions) {
    const execution = {
      id: `${runId}-${item.split}-${item.role}-${item.attempt}`,
      runId,
      suiteDigest,
      baselineRevision: frozen.baselineRevision,
      candidateDigest: candidate.digest,
      promptDigest: createHash("sha256")
        .update(promptByRoleAndSplit.get(`${item.role === "train-candidate" ? "candidate" : item.role}:${item.split}`))
        .digest("hex"),
      role: item.role,
      attempt: item.attempt
    };
    const prompt = promptByRoleAndSplit.get(`${item.role === "train-candidate" ? "candidate" : item.role}:${item.split}`);
    const promptBytes = Buffer.from(prompt);
    const promptFilename = `${execution.id}.prompt.txt`;
    const promptFile = path.join(outputDir, promptFilename);
    await writeFile(promptFile, promptBytes, { mode: 0o600, flag: "wx" });
    const promptDigest = createHash("sha256").update(promptBytes).digest("hex");
    const request = {
      binaryDigest: binary.digest,
      binaryPath: resolvedBinary,
      codexHomePath,
      execution,
      gid: runAs.gid,
      homePath,
      model,
      promptDigest,
      promptPath: promptFile,
      uid: runAs.uid
    };
    const filename = `${execution.id}.request.json`;
    const file = path.join(outputDir, filename);
    const bytes = Buffer.from(`${JSON.stringify(request, null, 2)}\n`);
    await writeFile(file, bytes, { mode: 0o600, flag: "wx" });
    records.push({
      executionId: execution.id,
      role: item.role,
      attempt: item.attempt,
      promptDigest: execution.promptDigest,
      prompt: promptFile,
      request: file,
      requestDigest: createHash("sha256").update(bytes).digest("hex"),
      executionId: execution.id
    });
  }
  const manifest = {
    schemaVersion: 2,
    repo: resolvedRepo,
    runId,
    model,
    binaryPath: resolvedBinary,
    binaryDigest: binary.digest,
    runtimePath: runtime.path,
    runtimeDigest: runtime.digest,
    runAs,
    purpose,
    suitePath: frozen.relativePath,
    sourceSuiteDigest: frozen.sourceDigest,
    targetSuitePath: target?.relativePath ?? null,
    targetSuiteDigest: target?.sourceDigest ?? null,
    suiteDigest,
    baselineRevision: frozen.baselineRevision,
    candidateDigest: candidate.digest,
    candidateFiles: candidate.files,
    requests: records
  };
  const manifestPath = path.join(outputDir, "attestation-requests.json");
  const manifestBytes = Buffer.from(`${JSON.stringify(manifest, null, 2)}\n`);
  await writeFile(manifestPath, manifestBytes, { mode: 0o600, flag: "wx" });
  return {
    ok: true,
    ...manifest,
    manifestPath,
    manifestDigest: createHash("sha256").update(manifestBytes).digest("hex"),
    executeCommand: [
      "sudo",
      "/bin/sh",
      "-c",
      HOST_ADMIN_SHELL,
      "better-workflows-admin",
      runtime.path,
      runtime.digest,
      manifestPath,
      createHash("sha256").update(manifestBytes).digest("hex")
    ]
  };
}
